bolt-db:
  container_name: bolt_db
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
    - MYSQL_DATABASE=bolt
bolt-server:
  container_name: bolt_server
  ports:
    - "80:80"
  links:
    - bolt-db
  image: bolt-server
