bolt-server:
  container_name: bolt_server
  ports:
    - "80:80"
  links:
    - bolt-db
  volumes:
    - "/var/bolt/app/config:/var/www/bolt/app/config"
    - "/var/bolt/app/theme:/var/www/bolt/app/theme"
  image: bolt-server
bolt-db:
  container_name: bolt_db
  image: mariadb
  volumes:
    - "/var/bolt/mysql:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=bolt
    - MYSQL_PASSWORD=bolt
    - MYSQL_DATABASE=bolt
